import math
from win32api import GetSystemMetrics

RES = WIDTH, HEIGHT = GetSystemMetrics(0), GetSystemMetrics(1)
# RES = WIDTH, HEIGHT = 1260, 640
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 100

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

FPS = 0
MOUSE_SENSI = 0.0001
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

PLAYER_POS = (3, 2)
PLAYER_SPEED = 0.003
PLAYER_SPRINT = 0.01
PLAYER_ANGLE = 0
PLAYER_SPEED_ROT = 0.002
PLAYER_SIZE_SCALE = 60
PLAYER_HEALTH = 100
PLAYER_LIVES = 2

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2
CEILING_COLOR = ( 55, 55, 55 )
FLOOR_COLOR = ( 156, 156, 156 )

STATUS_BAR_HEIGHT = (3 * HALF_HEIGHT // 2) // 3
## _ = WIDTH, HEIGHT
STATUS_BAR_DIGIT_SIZE =  HALF_WIDTH / 20, HALF_HEIGHT / 5
STATUS_BAR_WEAPON_SIZE = HALF_WIDTH // 3 - STATUS_BAR_DIGIT_SIZE[0] , STATUS_BAR_HEIGHT - STATUS_BAR_DIGIT_SIZE[1]
