
RES = WIDTH, HEIGHT = 1280, 720
BOX = 4
FPS = 60

WIDTH_HALF = WIDTH / 2
HEIGHT_HALF = HEIGHT / 2

BOX_H = (HEIGHT_HALF / 3) 

PADDING_HOR = WIDTH_HALF - (2 * BOX_H)
PADDING_VRT = HEIGHT_HALF - (2 * BOX_H)

NEW_BOX_COUNT = 2
